# Generated by Django 4.2 on 2023-05-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0002_orderbilling_billing_id_orderbilling_oreder_id'),
        ('product', '0002_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_info.category'),
            preserve_default=False,
        ),
    ]
