# Generated by Django 4.2 on 2023-05-02 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_review', message='review should be at least 20 characters and at most 200 characters', regex='^.{20,200}$')]),
        ),
    ]
