# Generated by Django 4.2 on 2023-05-03 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(code='invalid_description', message='product description should be at least 20 characters and at most 1000 characters', regex='^.{20,1000}$')]),
        ),
    ]
