# Generated by Django 4.2 on 2023-07-10 11:39

from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to=rules.file_uploader.wrapper),
            preserve_default=False,
        ),
    ]
