# Generated by Django 4.2 on 2023-05-02 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='This field must contain a valid phone number in the format 01(1 or 2 or 5 or 0)XXXXXXXX', regex='^01(0|1|2|5)\\d{8}$')]),
        ),
    ]
