# Generated by Django 4.2 on 2023-05-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
