# Generated by Django 4.2 on 2023-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
