# Generated by Django 4.2 on 2023-05-02 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(code='invalid_comment', message='comment should be at least 20 characters and at most 1000 characters', regex='^.{20,1000}$')]),
        ),
    ]
