# Generated by Django 4.2 on 2023-05-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbilling',
            name='billing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_info.billing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbilling',
            name='oreder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_info.order'),
        ),
    ]
