# Generated by Django 4.2 on 2023-05-02 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0003_delete_category_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='ZIP_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_code', message='The postal code must be five digits long', regex='^\\d{5}$')]),
        ),
    ]
