# Generated by Django 4.2 on 2023-05-02 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_info', '0004_alter_billing_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='ZIP_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_code', message='The postal code must be only five digits of numbers', regex='^\\d{5}$')]),
        ),
    ]
